### ISSUE TITLE
Installing problem Invalid object name 'information_schema.columns'.

### ISSUE THREAD

**Issue by barisakpunar** [ninianne98/CarrotCakeCMS-MVC#1]

**Comment by ninianne98** [comment]
what version of sql server are you  using?  does the sql credentials you are using have db owner rights?

see http://stackoverflow.com/questions/6023672/invalid-object-name-information-schema-columns-in-sql-server , http://stackoverflow.com/questions/3296428/changing-sql-server-collation-to-case-insensitive-from-case-sensitive , and http://www.sqlservercentral.com/Forums/Topic683866-146-1.aspx

**Comment by ninianne98** [comment]
I've been able to reproduce the error by changing the db collation from case insensitive to case sensitive:
 Invalid object name 'information_schema.columns'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: Invalid object name 'information_schema.columns'.

I've run this in sql:
SELECT name, collation_name 
FROM sys.databases
where name = 'CarrotCakeMVC'

it yields SQL_Latin1_General_CP1_CI_AS as the collation_name 

I created a new DB named CarrotCMS1 same as all other databases I use, before any tables were added I ran:
ALTER DATABASE CarrotCMS1 
   COLLATE SQL_Latin1_General_CP1_CS_AS

and then ran the source code, I got the error.

If you run
ALTER DATABASE CarrotCMS1 -- your db name here
   COLLATE SQL_Latin1_General_CP1_CI_AS -- or take whatever your current collation is and change the _CS_ to _CI_ it should start working (case sensitive to case insensitive)

**Comment by barisakpunar** [comment]
Thank you. The problem solved.
