### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by httpnotonly** [ninianne98/CarrotCakeCMS-MVC#3]
https://github.com/ninianne98/CarrotCakeCMS-MVC/blob/95094241b89ca9a5f070df2a50e6514448605732/PluginPhotoGallery/Controllers/AdminController.cs#L131

**Comment by httpnotonly** [comment]
POST base64(payload) -> XSS

**Comment by ninianne98** [comment]
This is within an authenticated admin area vs a publicly facing api, and only provides metadata storage on a per filename basis, and would not be returned except through said image URI being included in a gallery being presented back to the UI.  Though all the same, blocking certain file patterns to prevent undesirable file data is not unreasonable.

**Comment by ninianne98** [comment]
changes made in commit https://github.com/ninianne98/CarrotCakeCMS-MVC/commit/425d8fa639eec49356cfa5a309da66e951367f79

**Comment by httpnotonly** [comment]
Seems like path traversal fix
Can we make the CVE?

**Comment by ninianne98** [comment]
1) gallery name does not accept inputs with html  ex < and > - .net yellow screen will result
2) yes, there is an image metadata entry popup, which accepts < and > but at present, the front end does not actually honor outputting this data to the front end, an authenticated user would have to have entered something here (or SQL was bypassed), and in the backend, display is localized to the input fields, and form posts also use ValidateAntiForgeryToken (again, also requires the user to be authenticated to post changes)
3) the application credentials (server/site/sql) would have to be defeated to insert something to bypass the current catches, and as far as path traversal - that will block external image inclusion or attempts to force images outside of the allowed browsable folders
4) if the user does update any of the views to output the metadata, they would have to wrap the model properties in @Html.Raw to cause  content with < and > aka html markup to render in a way to effect XSS, simply outputting the model values would not @model.ImageMetaData would show raw html vs @Html.Raw(model.ImageMetaData) which would produce browser renderable html as ImageMetaData  is a string not an IHtmlString
5) the image names themselves are output wrapped in @HttpUtility.UrlEncode when in image tags
